GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
  | Name     | Type               | Params
------------------------------------------------
0 | lstm     | LSTM               | 316 K
1 | fc       | Linear             | 650
2 | accuracy | MulticlassAccuracy | 0
------------------------------------------------
317 K     Trainable params
0         Non-trainable params
317 K     Total params
1.269     Total estimated model params size (MB)
C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:441: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
Traceback (most recent call last):
  File "C:\Users\fatih\PycharmProjects\model_implementation\main.py", line 100, in <module>
    trainer.fit(model, data_module)
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\trainer\call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 987, in _run
    results = self._run_stage()
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\loops\utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\trainer\call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 412, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "C:\Users\fatih\PycharmProjects\model_implementation\LSTMModel.py", line 44, in validation_step
    self.valid_acc(logits, y)
  File "C:\Users\fatih\PycharmProjects\model_implementation\venv\lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LSTMModel' object has no attribute 'valid_acc'
Sanity Checking DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]